function [yColl,dyColl]=collocate_all_reactors(t, y, tyRow, opt)
    arguments
        t (:,1) double;
        y (:,:) double; 
        tyRow (:,2) uint64;
        opt.kernelStr (1,:) char {mustBeMember(opt.kernelStr,{'EpanechnikovKernel',...
                                                      'UniformKernel',...
                                                      'TriangularKernel',...
                                                      'QuarticKernel',...
                                                      'TriweightKernel',...
                                                      'TricubeKernel',...
                                                      'GaussianKernel',...
                                                      'CosineKernel',...
                                                      'LogisticKernel',...
                                                      'SigmoidKernel',...
                                                      'SilvermanKernel'})} = 'EpanechnikovKernel'
    end
    
    nReactors = size(tyRow,1);

    yColl = zeros(size(y));
    dyColl = zeros(size(y));
    
    for i = 1:nReactors
        [yColl(tyRow(i,1):tyRow(i,2),:), dyColl(tyRow(i,1):tyRow(i,2),:)] = collocate_data(y(tyRow(i,1):tyRow(i,2),:), t(tyRow(i,1):tyRow(i,2),1), opt.kernelStr); 
    end

end